version: 2.1
orbs:
  node: circleci/node@4.9.0
jobs:
  build-and-test:
    parameters:
      dependency_type:
        # Whether the test should build using the commit dependency versions or the latest builds.
        type: enum
        enum: ["package.json", "builds-repo"]
    docker:
      - image: cimg/node:14.18.3@sha256:30583ce79b08d318b1fc5e17a613d21ef960091e5442b06eb49c56fa180a3b30
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - node/install-packages:
          app-dir: integration/project
          pkg-manager: yarn
      - node/install-packages:
          app-dir: integration/pre_apf_project
          pkg-manager: yarn
      - node/install-packages:
          app-dir: integration/workspace
          pkg-manager: yarn
      - run: scripts/lint.sh
      - run: scripts/format.sh
      - run: scripts/build.sh << parameters.dependency_type >>
      - run: scripts/test.sh
workflows:
    build-and-test:
      jobs:
        - build-and-test:
            name: build-and-test
            dependency_type: "package.json"
    buid-and-test-against-builds:
      jobs:
        - build-and-test:
            name: build-and-test-builds-repo
            dependency_type: "builds-repo"
      triggers:
        - schedule:
            filters:
              branches:
                only:
                  - master
            # Runs monitoring jobs at 10:00AM every day.
            cron: '0 10 * * *'
    
